### PR TITLE
Document Terser plugin

### PR DESCRIPTION
**Pull request by probins**
Have I forgotten anything?

Best not to merge this until the plugin has been pushed to `deno.land/x` 😄

### CODE REVIEW

**Comment by oscarotero** [comment]
I think it's fine. One question: this only works for `.js` files, right? (not `.ts`).

**Comment by probins** [comment]
https://github.com/terser/terser/issues/840 - unless there's some way to use Deno's TS compiler? I just took a quick look for a web service that runs the compiler and returns js, but couldn't find one.

**Comment by probins** [comment]
[`Deno.compile()`](https://deno.land/manual/runtime/compiler_apis) could be used. You could have another plugin: if the input is TS, run the compile plugin and pipe the output into Terser. I'll leave that to someone else, as I have 0 interest in TS.

**Comment by oscarotero** [comment]
I think [Deno.transpileOnly](https://deno.land/manual/runtime/compiler_apis#codedenotranspileonlycode) is better, because only traspile the code and output modern ES6 javascript.
Anyway, I'm not interested in TS either, and I'm ok with a different plugin for that

**Comment by probins** [comment]
`denopack` https://github.com/denofn/denopack/tree/main/plugin has 2 different plugins, one for `compile()` and one for `transpile()`. Then users can pick whichever they like.

**Comment by oscarotero** [comment]
I just released the `v0.11.0` version, that includes this plugin, so when you change the documentation with the new configuration options, I'll merge it.

**Comment by probins** [comment]
Updated - you can squash these commits, right? I edited this online in Github, which doesn't have the facility to change/amend commits.

**Comment by oscarotero** [comment]
Yes, no problem.
Thank you!

**Pull request merged**
